groups:

- name: docker

  rules:

  - alert: ContainerDown

    expr: up{job="cadvisor"} == 0

    for: 2m

    labels:
      severity: critical

    annotations:

      summary: Container Metrics Unavailable

  - alert: HighContainerCPU

    expr: rate(container_cpu_usage_seconds_total{name!=""}[5m]) > 0.9

    for: 5m

    labels:
      severity: warning

    annotations:

      summary: Container CPU High

  - alert: HighContainerMemory

    expr: container_memory_usage_bytes{name!=""} > 1000000000

    for: 5m

    labels:
      severity: warning

    annotations:

      summary: Container Memory High

  - alert: ContainerRestartLoop

    expr: increase(container_start_time_seconds{name!=""}[15m]) > 2

    for: 5m

    labels:
      severity: warning

    annotations:

      summary: Container Restart Loop