########################################
# Project
########################################

PROJECT_NAME=MSAR

PROJECT_ROOT=/opt/msar

########################################
# Docker
########################################

COMPOSE_FILE=compose/docker-compose.yml

COMPOSE_PROD_FILE=compose/docker-compose.prod.yml

########################################
# Images
########################################

BACKEND_IMAGE=ghcr.io/khalid-786/msar-api

FRONTEND_IMAGE=ghcr.io/khalid-786/msar-frontend

########################################
# Health

########################################

API_HEALTH=http://localhost:5080/health

FRONTEND_HEALTH=http://localhost

########################################
# Logs

########################################

LOG_DIRECTORY=logs

########################################
# Backup

########################################

BACKUP_DIRECTORY=backup

########################################
# Release

########################################

RELEASE_DIRECTORY=releases