services:

  ############################################################
  # Backend Blue
  ############################################################

  backend-blue:

    image: ${BACKEND_IMAGE}

    container_name: msar-api-blue

    restart: unless-stopped

    env_file:
      - /root/msar/config/.env.production

    expose:
      - "80"

    networks:
      - msar-network

  ############################################################
  # Frontend Blue
  ############################################################

  frontend-blue:

    image: ${FRONTEND_IMAGE}

    container_name: msar-frontend-blue

    restart: unless-stopped

    depends_on:

      backend-blue:
        condition: service_started

    expose:
      - "80"

    networks:
      - msar-network

networks:

  msar-network:
    external: true