global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

########################################################
# Alert Rules
########################################################

rule_files:

  - /etc/prometheus/rules/infrastructure.yml
  - /etc/prometheus/rules/docker.yml
  - /etc/prometheus/rules/application.yml
  - /etc/prometheus/rules/rabbitmq.yml
  - /etc/prometheus/rules/sqlserver.yml

########################################################
# Alertmanager
########################################################

alerting:

  alertmanagers:

    - static_configs:

        - targets:

            - alertmanager:9093

########################################################
# Scrape Jobs
########################################################

scrape_configs:

########################################################
# Prometheus
########################################################

- job_name: prometheus

  static_configs:

    - targets:

        - prometheus:9090

########################################################
# Node Exporter
########################################################

- job_name: node-exporter

  static_configs:

    - targets:

        - node-exporter:9100

########################################################
# cAdvisor
########################################################

- job_name: cadvisor

  static_configs:

    - targets:

        - cadvisor:8080

########################################################
# ASP.NET API
########################################################

- job_name: api

  metrics_path: /metrics

  static_configs:

    - targets:

        - msar-api:80

########################################################
# RabbitMQ Exporter
########################################################

- job_name: rabbitmq

  static_configs:

    - targets:

        - rabbitmq-exporter:9419

########################################################
# Loki
########################################################

- job_name: loki

  static_configs:

    - targets:

        - loki:3100

########################################################
# Alertmanager
########################################################

- job_name: alertmanager

  static_configs:

    - targets:

        - alertmanager:9093